theme: jekyll-theme-architect
title: [Luca Ardito]
description: [Associate Professor / Software Engineer / Mobile Developer]

github:
  repository_url: https://github.com/lucaardito/
  repository_name: [Luca Ardito]
